### ISSUE TITLE
How to deal with Retrofit's suspend and error handling with Coroutines?

### ISSUE THREAD

**Issue by mustaqimM** [udacity/andfun-kotlin-mars-real-estate#9]
I saw that https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/ is now deprecated and the recommended way is using the suspend keyword on a service interface funtion. Retrofit can directly return a `List<MarsProperty>` but then how would errors be handled?

**Comment by Raznic** [comment]
I believe there are a couple of approaches for handling errors in coroutines.

## Option 1: Try/Catch

Just like in the lab exercise, we can use a `try/catch` block to handle any errors that pop-up. 

```kotlin
private fun getMarsRealEstateProperties() {
    coroutineScope.launch {
        try {
            val listResult  = MarsApi.retrofitService.getProperties()
            _response.value = "Success: ${listResult.size} Mars properties retrieved"
        } catch (e: Exception) {
            _response.value = "Failure: ${e.message}"
        }
    }
}
```

## Option 2: CoroutineExceptionHandler

We can pass a [CoroutineExceptionHandler](https://kotlinlang.org/docs/reference/coroutines/exception-handling.html#coroutineexceptionhandler) context object when creating a new coroutine. This will get attached to the root coroutine and handle any uncaught exceptions that propagate their way up. 

```kotlin
private fun getMarsRealEstateProperties() {
    coroutineScope.launch(CoroutineExceptionHandler { _, exception ->
        _response.value = "Failure: ${exception.message}"
    }) {
        val listResult =  MarsApi.retrofitService.getProperties()
        _response.value = "Success: ${listResult.size} Mars properties retrieved"
    }
}
```

Note that I changed the code a bit to use a Job instead of a Deferred like in the lab guide. Jobs are executed synchronously, which is fine for this use-case since there's only a single network call. If I wanted to use a Deferred, I could change my code to the following:

```kotlin
val getPropertiesDeferred =  async { MarsApi.retrofitService.getProperties() }
val listResult = getPropertiesDeferred.await()
_response.value = "Success: ${listResult.size} Mars properties retrieved"
```

When I tested it out I didn't have any issues using a Deferred with Option 2. The CoroutineExceptionHandler caught the exception and set the failure text correctly. Option 1, on the other hand, crashes if you try wrapping the Deferred in a `try/catch`. I didn't really dig into the cause since Option 2 worked for me and is my preferred method. My best guess is it has something to do with how Deferred encapsulate exceptions.

**Comment by mustaqimM** [comment]
thanks so much for this. It looks like the best way would be to use a `CoroutineExceptionHandler`
